package com.ldapadmin.entity.enums;

/**
 * Indicates how an {@link com.ldapadmin.entity.AuditEvent} was generated.
 */
public enum AuditSource {
    /** Generated by LDAPAdmin when an admin performs a write via the REST API. */
    INTERNAL,
    /** Read from an LDAP directory's {@code cn=changelog} by the changelog poller. */
    LDAP_CHANGELOG
}
