package com.ldapadmin.entity.enums;

public enum ReportType {
    USERS_IN_GROUP,
    USERS_IN_BRANCH,
    USERS_WITH_NO_GROUP,
    RECENTLY_ADDED,
    RECENTLY_MODIFIED,
    RECENTLY_DELETED,
    DISABLED_ACCOUNTS,
    MISSING_PROFILE_GROUPS,
    SOD_VIOLATIONS,

    // Audit reports
    USER_ACCESS_REPORT,
    ACCESS_REVIEW_SUMMARY,
    PRIVILEGED_ACCOUNT_INVENTORY,
    ACCESS_DRIFT_REPORT,
    AUDIT_LOG_REPORT
}
